version: "3.8"

services:
  app_blue:
    image: "${BLUE_IMAGE}"
    container_name: app_blue
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT}
      - APP_POOL=blue
    ports:
      - "${BLUE_PORT}:${PORT}"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${PORT}/healthz"]
      interval: 5s
      timeout: 3s
      retries: 2

  app_green:
    image: "${GREEN_IMAGE}"
    container_name: app_green
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT}
      - APP_POOL=green
    ports:
      - "${GREEN_PORT}:${PORT}"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${PORT}/healthz"]
      interval: 5s
      timeout: 3s
      retries: 2

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "${PUBLIC_PORT}:80"
    volumes:
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
      - nginx_logs:/var/log/nginx    # <-- shared volume for real logs
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - APP_PORT=${PORT}
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    depends_on:
      - app_blue
      - app_green
    networks:
      - app_network

  alert_watcher:
    build: ./watcher
    container_name: alert_watcher
    volumes:
      - nginx_logs:/var/log/nginx:ro
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ACTIVE_POOL=${ACTIVE_POOL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD:-2}
      - WINDOW_SIZE=${WINDOW_SIZE:-200}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC:-300}
    depends_on:
      - nginx
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  nginx_logs:
